# настройки обрабатывания соединение нджинкс
events {
    worker_connections 1024;
}

http {
# бэкэнд сервера куда нджинкс перенаправляет запросы
    upstream flask_app {
        server unix:/tmp/uwsgi.sock;
    }
# определение виртуального хоста
    server {
        listen 80;
        server_name _;
# обработка / всех запросов
        location / {
            include uwsgi_params;
            uwsgi_pass unix:/tmp/uwsgi.sock;
            uwsgi_param Host $host;
            uwsgi_param X-Real-IP $remote_addr;
        }
# обработка /api всех запросов
        location /api/ {
            include uwsgi_params;
            uwsgi_pass unix:/tmp/uwsgi.sock;
            uwsgi_param Host $host;
            uwsgi_param X-Real-IP $remote_addr;
            
            add_header X-Cache-Status "MISS (uwsgi mode)";
        }
# обработка статических запросов
        location /static {
            alias /app/app/static;
        }
    }
}